---
  - name: config VM with docker
    hosts: elk
    remote_user: azadmin
    become: true
    tasks:

    - name: Use more memory
      sysctl:
        name: vm.max_map_count
        value: '262144'
        reload: yes

    - name: install docker.io
      apt:
        name: docker.io
        state: present
        update_cache: yes
        force_apt_get: yes

    - name: install pip3
      apt:
        force_apt_get: yes
        name: python3-pip
        state: present

    - name: install python docker module
      pip:
        name: docker
        state: present

    - name: install elk docker container
      docker_container:
        name: elk
        image: sebp/elk:761
        state: started
        restart_policy: always
        published_ports:
          - 5601:5601
          - 9200:9200
          - 5044:5044

    - name: enable docker service
      systemd:
        name: docker
        enabled: yes
